### ISSUE TITLE
KeePass 2.50

### ISSUE THREAD

**Issue by SorrySomethingWentWrong** [adrium/KeepassPfpConverter#5]
The new version KeePass 2.50 does not permit to use of the latest version of this plug-in.

**Comment by adrium** [comment]
Can not reproduce with version 2.50. Kindly asking to reopen with a detailed description.

![plugin](https://user-images.githubusercontent.com/23739584/154132544-214faa4f-6ff5-4ab9-8061-257d7c091f0d.png)

![import](https://user-images.githubusercontent.com/23739584/154132555-b798b193-9761-423c-a0f6-f891a81c2a41.png)
